### ISSUE TITLE
using boxes in python virtual environment

### ISSUE THREAD

**Issue by dido77-arduino** [eridur-de/mightyscape-1.2#144]
Hi

I would like to use the plugin in a python virtual environment, I am not successful at the moment.

I have setup the venv, cloned the repo and installed the requirements as  needed

`source $HOME/venv/bin/activate`
`cat ~/.config/inkscape/extensions/mightyscape-1.2/requirements.txt | sed '/^#/d' | xargs -n 1 pip install --upgrade  --no-cache-dir` (completed w/o errors)

I have also changed preferences.xml to use the virtual environment
```<group
       id="aboutextensions"
       python-interpreter="/home/username/venv/bin/python" />
```

When I start inkscape and I try any of the Boxes plugins, I receive the error

```
File` "/home/didomax/.config/inkscape/extensions/mightyscape-1.2/extensions/fablabchemnitz/boxes.py/boxes/scripts/boxes", line 24, in <module>
    import boxes
ModuleNotFoundError: No module named 'boxes'
```
I tried another plugin (Origami) and it worked w/o glitches.

Where am I missing a step

Thanks
Max

**Comment by vmario89** [comment]
Hi,
can you ensure that boxes installed properly? Maybe it skipped installing due to some error reason?

you can check by

`pip list installed | grep boxes`

**Comment by dido77-arduino** [comment]
Hi @vmario89 

actually no, it was not installed - I was assuming it was part of the requirements.txt, my bad.

I have now tried to install it, but it does not sound to me right

```
pip install boxes --no-cache-dir
Collecting boxes
  Downloading boxes-0.0.0.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: boxes
  Building wheel for boxes (setup.py) ... done
  Created wheel for boxes: filename=boxes-0.0.0-py2.py3-none-any.whl size=3111 sha256=bb45319bd050d01002096f3dff2e5f39b43837aed0a923373f972bea94cfc797
  Stored in directory: /tmp/pip-ephem-wheel-cache-a29pnob1/wheels/36/5e/21/04cf0e4703e07bb629c779f063126fb5a618b66d19071dfc38
Successfully built boxes
Installing collected packages: boxes
Successfully installed boxes-0.0.0
```

And actually boxes.py is empty

```
cat venv/lib64/python3.10/site-packages/boxes/boxes.py 
# -*- coding: utf-8 -*-

"""Main module."""
```

Any clue what is going on?

Max

**Comment by vmario89** [comment]
hi, you actually installed the wrong boxes module: https://pypi.org/project/boxes/

please try to install like the following command:
```
pip install git+https://github.com/florianfesti/boxes.git
```

then run
```
boxes
```

the output will be
```

boxes.py

Generate stencils for wooden boxes.

Usage:
  boxes <generator> [<args>...]
  boxes --list
  boxes (-h | --help)
  boxes --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --list        List available generators.
```

**Comment by vmario89** [comment]
ps: i added the missing dependency in requirements.txt

**Comment by dido77-arduino** [comment]
Thanks for the prompt answer. 

Some progress done, I can call boxes both from the command line and in the python (virtual) environment 

```
$ boxes.py

Generate stencils for wooden boxes.

Usage:
  boxes <generator> [<args>...]
  boxes --list
  boxes (-h | --help)
  boxes --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --list        List available generators.
```

and

```
Python 3.11.7 (main, Jan  7 2024, 01:05:16) [GCC 13.2.1 20231216] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boxes
>>> 
```

However, I get the very same error as in the previous post when trying to run the extension within inkscape. My preferences.xml

```
<group
     id="extensions"
     org.inkscape.output.png.inkscape.png_bitdepth="99"
     org.inkscape.output.png.inkscape.png_compression="6"
     org.inkscape.output.png.inkscape.png_antialias="2"
     python-interpreter="/home/didomax/venv/bin/python"
```

I do not know anymore where to look for issues...

**Comment by vmario89** [comment]
looks like i will have to check it myself when using venv (actually never tried). Which OS are you running? Linux, Windows, ... ?

**Comment by dido77-arduino** [comment]
Gentoo Linux with python 3.11.

Thanks
Max

9 Feb 2024 09:07:11 Mario Voigt ***@***.***>:

**Comment by vmario89** [comment]
i tested the thing with venv and it can confirm the failure. but good news: most of plugins work really well with venv. i will change mightyscape documentation to use venv mainly because it does not mess with system libraries at all

**Comment by vmario89** [comment]
finally fixed by https://github.com/eridur-de/mightyscape-1.2/commit/c5e4801249efa607e09a24ff9885584208a9adec
